### PR TITLE
Wrong minimum fee

### PR DESCRIPTION
**Pull request by nferruzzi**
configure the proper minimum fee to match 0.1 xvg (was 1 xvg)

### CODE REVIEW

**Comment by buzztiaan** [comment]
also on all other versions of electrum plz :P

**Comment by nferruzzi** [comment]
Ok, but wouldn't it be cool to say "the fee on the tor one is 1/10" to move people on it ;) ? anyway going to do it now :)

**Comment by buzztiaan** [comment]
rofl, travis looked pretty f'd :P but thanks for the PR's on the others! 
now we wait till dev un-coma's

**Comment by nferruzzi** [comment]
Unfortunately the tests fails without the patch too... at least on my local checkout

**Comment by buzztiaan** [comment]
Ah well, guess it never worked

**Pull request merged**
