### PR TITLE
Fix CORS JSONRPC bug

### PR DESCRIPTION
**Pull request by ali-raheem**
Fixing electrum bug.

### CODE REVIEW

**Comment by underdarkskies** [comment]
This is great. There is one more branch of electrum. Can you please hit that one too?

**Comment by underdarkskies** [comment]
Nevermind

**Comment by justinvforvendetta** [comment]
@underdarkskies he got the other one already

**Comment by underdarkskies** [comment]
I2p has no jsonrpc.py

**Comment by underdarkskies** [comment]
@justinvforvendetta when can we compile and release new clients including this commit? 2.4.1 looking pretty stale still

**Pull request merged**
